defaults:
  - _self_
  - data@data_0: SEED
  - data@data_1: None
  - data@data_2: None
  - data@data_3: None
  - data@data_4: None
  - data@data_val: SEEDV

log:
  run_name: 'mlla_dgl_fusion_v1'
  mlp_cp_dir: 'mlp_cp'

data_cfg_list:

train:
  seed: 19260832
  n_fold: 1
  n_pairs: 1024
  n_gpu_use: 4
  iftest: False
  lr: 3e-4
  wd: 0.004
  max_epochs: 50
  min_epochs: 10
  num_workers: 16
  save_interval: 5
  loss:
    temp: 0.15
    w_sim: 1.0
    w_rec: 1.0
    w_cda: 0.0
    mask_ratio: 0.25
    clisa_loss: True
    CDA_loss: True
    CDA_factor: 1.0
    to_riem: False

val:
  n_fold: '1->3'
  extractor:
    use_pretrain: True
    ckpt_epoch: 10
    ckpt_tag: v4
    reverse: True
    normTrain: False
    batch_size: 64
    fea_mode: 'me'
    rn_decay: 0.990
    LDS: True
  mlp:
    seed: 19260817
    lr: 0.0005
    wd: 0.0022
    hidden_dim: 128
    out_dim: ${data_val.n_class}
    batch_size: 256
    max_epochs: 25
    min_epochs: 2
    num_workers: ${train.num_workers}

model:
  in_channels: 60
  time_length: 625
  architecture: 'DGE_Net_vFinal'

  hybrid:
    num_blocks: 4
    dropout: 0.1
    topk: 8
    space_heads: 4
    time_heads: 4
    gat_bchunk: 4

  MLLA:
    patch_size: 32
    patch_stride: 6
    hidden_dim: 128
    out_dim: 32
    depth: 2
    n_heads: 8
    uni_channels: [
      "FP1", "FPZ", "FP2", "AF3", "AF4", "F7", "F5", "F3", "F1", "FZ",
      "F2", "F4", "F6", "F8", "FT7", "FC5", "FC3", "FC1", "FCZ", "FC2",
      "FC4", "FC6", "FT8", "T7", "C5", "C3", "C1", "CZ", "C2", "C4",
      "C6", "T8", "TP7", "CP5", "CP3", "CP1", "CPZ", "CP2", "CP4", "CP6",
      "TP8", "P7", "P5", "P3", "P1", "PZ", "P2", "P4", "P6", "P8",
      "PO7", "PO5", "PO3", "POZ", "PO4", "PO6", "PO8", "O1", "OZ", "O2"
    ]